### ISSUE TITLE
Need a good README

### ISSUE THREAD

**Issue by eriksteinmetzataugsburg** [wowbob396/sc2ai#1]
We should have a good readme in here explaining what this is, what is in it, and how to start using it.

**Comment by branberry** [comment]
Will do, and I'll also make sure to start commenting the code we have so far.

**Comment by eriksteinmetzataugsburg** [comment]
Thanks,

Oddly, I could not figure out how to assign it to you in the GitHub interface. Are you able to assign it (to yourself or others)?

Erik

**Comment by skerlin** [comment]
Should be this gear on the right side -->
![image](https://user-images.githubusercontent.com/12833680/47875525-c1e39680-dde4-11e8-84b8-7b5a0dddacf0.png)

**Comment by eriksteinmetzataugsburg** [comment]
Thanks!

I suspect my permissions aren’t high enough, as my interface does not include any gears on the right:

**Comment by branberry** [comment]
Hey @eriksteinmetzataugsburg, check your Augsburg email and there should be a request to join as a collaborator.  Once you accept the invitation, you should have permission

**Comment by eriksteinmetzataugsburg** [comment]
Yeppers, that worked. I just dove right in looking at the repo from the link in that email before I accepted. Thanks for clearing up the process!
